### ISSUE TITLE
"Type[xxx]" has no attribute "from_json"

### ISSUE THREAD

**Issue by gjcarneiro** [lidatong/dataclasses-json#23]
One of the downsides of @dataclass_json is that mypy doesn't know about the extra `from_json` and `to_json` methods.  Any chance this can be supported, somehow?

The docs seem to suggest there is a plugin system in mypy, albeit experimental: https://mypy.readthedocs.io/en/latest/extending_mypy.html#extending-mypy-using-plugins

```
@dataclass_json
@dataclass
class BulkApmm:
    id: str
    frequency_ms: int
    pmms: List[Apmm]

...

    bulk_apmm = BulkApmm.from_json(await request.text())

betslipdisp/views.py:70: error: "Type[BulkApmm]" has no attribute "from_json"
```

**Comment by lidatong** [comment]
Hi, yes: I'd like this package to have full support for `typing` in the future. The "official" way to do that way would be to follow PEP 561 or provide a stub (`.pyi` file) containing type information, so there definitely is a way. It does require introducing typing to all packages and sub-packages, so it's a fair amount of work.

Without the above, `mypy` treats the package as "untyped" and will output a message along the lines of `Cannot find module dataclasses_json`. Basically, `mypy` treats a package as missing if there are no associated typing stub files.

**But this is somewhat tangential to your code example / use case:**
In your example, you're using the `dataclass_json` class decorator approach rather than the the mixin, which is absolutely fine (I personally find stacking decorators syntactically nicer), except mypy currently has particularly weak support for decorators (see this [issue](https://github.com/python/mypy/issues/3157)). So even with a typing stub, it won't be able to typecheck using this library's `dataclass_json` class decorator.

Something like the following should be valid:
```python
from typing import Type, TypeVar

A = TypeVar('A')
DC = TypeVar('DC', bound=DataClassJsonMixin)

def dataclass_json(f: Type[A]) -> Type[DC]:
    ...
```
such that `dataclass_json`'s type signature says "it's a function that takes in a type and returns a type that implements dataclass_json" (i.e. a class decorator). And the type variable `DC` captures the concrete implementation of the `DataClassJsonMixin` (`BulkApmm` in your example).

But `mypy` actually still won't recognize `.to_json()` as a method, even with the above. It'll only type-check if you inherit the mixin directly.

Indeed, the state of typing in Python is not yet where I wish it were.

**Comment by lidatong** [comment]
Tracking in parent issue #31
