### ISSUE TITLE
`TypeError` whenever using modern type annotations

### ISSUE THREAD

**Issue by FrancescoCasalegno** [lidatong/dataclasses-json#327]
## Summary
Whenever I try to use modern type annotations (e.g. `str | None` instead of `Optional[str]`)  in a class inheriting from `DataClassJSONMixin` I get a `TypeError`.

Notice that these modern type annotations (see [PEP 604](https://www.python.org/dev/peps/pep-0604/) and [PEP 585](https://www.python.org/dev/peps/pep-0585/)) are available since `Python 3.9+` without even need for `from __future__ import annotations`. And since you declare that you support `Python 3.6+`, then I think this `TypeError` should be fixed:
https://github.com/lidatong/dataclasses-json/blob/884b89f3b587b23a0e5e30c595eb70fb3838d26e/setup.py#L25

## Reproduce the Error
The following can be reproduced on `Python 3.7+`.

### Example 1
```python
from __future__ import annotations
from mashumaro import DataClassJSONMixin

class MyClass(DataClassJSONMixin):
    arg1: str | None

...

TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
```

### Example 2
```python
from __future__ import annotations
from mashumaro import DataClassJSONMixin

class MyClass(DataClassJSONMixin):
    arg1: tuple[int, int]

...

TypeError: 'type' object is not subscriptable
```

**Comment by Fatal1ty** [comment]
Hi @FrancescoCasalegno

I think you created the issue in the wrong project. But as an author of [mashumaro](https://github.com/Fatal1ty/mashumaro) that you use in the provided code snippet, I can help with your problem.

PEP 604 is currently not supported. It will be fixed soon.
PEP 585 is supported since version [2.8 released](https://github.com/Fatal1ty/mashumaro/releases/tag/v2.8). Make sure you are not using an older version.

**Comment by FrancescoCasalegno** [comment]
Hi @Fatal1ty, my apologies, you're right this is the wrong project!

Thank you a lot for your tip, I am still having the PEP 585 error on Python 3.7 (not on Python 3.9 though). I will close this and open an issue in the right place.
