### ISSUE TITLE
to_json() includes the fields marked with repr=True also 

### ISSUE THREAD

**Issue by mhtocs** [lidatong/dataclasses-json#333]
Hi,

to_json() doesnt work as expected

Please consider the following example

```python
from datetime import datetime
from dataclasses import dataclass, field
from dataclasses_json import dataclass_json
@dataclass_json
@dataclass
class Session:
    topic: str
    startTimeInSec: int = field(repr=False)
    startTime: str = field(init=False)

    def __post_init__(self):
        format = "%b %d, %Y %H:%M %p"
        self.startTime = f'{datetime.fromtimestamp(self.startTimeInSec).strftime(format)}'

session = Session(topic="hello world", startTimeInSec=1643404065)

session.to_json()
```

#### Current Output:

```python
{"topic": "hello world", "startTimeInSec": 1643404065, "startTime": "Jan 29, 2022 02:37 AM"}
```

#### Expected Output:

```python
{"topic": "hello world", "startTime": "Jan 29, 2022 02:37 AM"}
```

As `startTimeInSec` field is marked with `repr` as `False`, It should not be included when converting the object to json. 

Or Is there a different way to achieve what i am trying to do?

**Comment by USSX-Hares** [comment]
IMAO, this is working as intended – DCJ's method `to_json` serializes data so it can then be deserialized.

Otherwise, the following won't work:
```python
j = session.to_json()
s2 = Session.from_json(j)
```
Here, TypeError (or other) would be reised because the required field `startTimeInSec` was not provided in the JSON.

What you looking for, is, probably:
 * Constructor overload on the class-level
 * Coder/decoder overload on the DCJ level
 * `__repr__` method overload on the class-level
 * Properties with getters/setters for the class
