### ISSUE TITLE
Encode default values from dataclass

### ISSUE THREAD

**Issue by HappyTreeBeard** [lidatong/dataclasses-json#49]
The [README.md discusses](https://github.com/HappyTreeBeard/dataclasses-json/blob/master/README.md#handle-missing-or-optional-field-values-when-decoding) using default values when decoding JSON but can a dataclass object encode to JSON using default values set by the dataclass constructor? 

```python

from dataclasses import dataclass
from dataclasses_json import dataclass_json

@dataclass_json
@dataclass
class Person:
    name: str = 'x'

# Encoding to JSON using default name value
Person().to_json()  # '{"name": "x"}'
```

**Comment by lidatong** [comment]
Hi, yes, it will encode the way you described (i.e. `Person().to_json()  # '{"name": "x"}'`). It does that not because the library is doing anything special, but because it's impossible in general to create a Person object with the field `name` unset. For example, it will either raise an Exception (if you omit the required argument to the constructor) or default to 'x' if you force that default. So the object will be encoded with that field no matter what. Let me know if that makes sense.

**Comment by HappyTreeBeard** [comment]
> Hi, yes, it will encode the way you described (i.e. `Person().to_json() # '{"name": "x"}'`). 

I thought I had tested this earlier and found the behavior to be different but I must have been mistaken.
